% Comparing the norms of details generated by the two multiscale transforms

clear;
close all;
tic;

% Setting the sampling level and truncation parameter
n       =    15;
eps     =    3;

% Workspace
range        =    linspace(1, n-1, n-1);
norms        =    zeros(n, 2);

% Applying the two different transforms
pyramid             =  Wavelet(n, eps);
pyramid_invariant   =  Wavelet(n, eps, 'A');

% Calculating the norms
for i = 1 : n
   norms(i, 1)            =  max(abs(pyramid{i, 1}));
   norms(i, 2)            =  max(abs(pyramid_invariant{i, 1}));
end

% Plotting the results
figure(1); hold on; grid on;
plot(range, log10(norms(2:end,1)),'-.r','LineWidth',2);
plot(range, log10(norms(2:end,2)),'b','LineWidth',2);
xlim([1 n-1]);
xlabel('Level of details -- $\ell$','interpreter','latex');
ylabel('$\|d^{(\ell)}\|_\infty$','interpreter','latex');
set(gca,'fontsize',14);

% Changing labels on y-axis
yt     =  str2double(arrayfun(@num2str,get(gca,'ytick'),'un',0));
labels =  arrayfun(@(yt)sprintf('10^{%.1f}', yt), yt, 'uni', 0);
set(gca,'YTickLabel',labels);

fpath = 'D:\Git_Projects\Manifold-Multiscale-Representations\TRUNCATION_Multiscale_Representation\Generated_Images';
saveas(gcf,fullfile(fpath, 'truncation_comparison'),'fig');
hold off;

toc;


